service: task-12-sqs-implementation

provider:
  name: aws
  runtime: python3.12
  profile: second-account
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:GetQueueUrl
        - sqs:ListQueues
      Resource: 
        - !GetAtt ProcessingQueue.Arn
    - Effect: "Allow"
      Action:
        - dynamodb:putItem
        - dynamodb:GetItem
      Resource: 
        - !GetAtt simpleProcessingQueueTable.Arn

resources:
  Resources:
    ProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: simple-processing-queue
        VisibilityTimeout: 30
        MessageRetentionPeriod: 345600
      
    simpleProcessingQueueTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: processed-text-data
        AttributeDefinitions:
          - AttributeName: processed_data
            AttributeType: S
        KeySchema:
          - AttributeName: processed_data
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      

functions:
  send_message:
    handler: handlers.handler.send_message
    events:
      - httpApi:
          path: /send
          method: post
  
  process_message:
    handler: handlers.handler.process_message
    events:
      - sqs:
          arn: !GetAtt ProcessingQueue.Arn
          batchSize: 1
